<div class="footer">
    <div class="cheese-icon-wrapper">
        <div class="cheese-icon"><img src="img/cheese-icon.png" alt=""></div>
    </div>
    <div class="copyright">
        <div>copyright &copy; <?php echo date('Y'); ?> danthecheeseman.com</div>
        <div>Orlando, Florida</div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
<script src="js/plugins.js"></script>
<script src="js/main.js?v=<?php echo time(); ?>"></script>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-105199636-1', 'auto');
    ga('send', 'pageview');
</script>
</body>
</html>