<?php include 'header.phtml' ?>

<div class="about">
    <div class="content">
        <div class="content-left">
            <h3>For The Love Of Cheeses</h3>
            <p>Often I’m asked, "What is a Certified Cheese Professional?" Like a Sommelier or a Cicerone, my job is to know all that there is about cheese. These are designations of expertise. Sommelier is a professional wine enthusiast; a Cicerone is fluent in all things beer. So as a Certified Cheese Professional, I am a professional cheese head.</p>
            <p>Accredited by the American Cheese Society. I am one of 800 certified cheese professionals. Whether it’s a question of a breed of animal, to what cracker is the best vehicle or if your cheese will melt. I am the one to answer these questions.</p>
            <p>I have tasted over 1,700 cheeses in my career and live by the compass that is my nose. I have made many friends in the industry and learned a great deal about beer and wine in the process. I love what I do. Promoting one of the world’s favorite foods and telling the story of how it came to you.</p>
        </div>

        <div class="content-right mobile-hide">
            <div class="content-icon">
                <img src="img/ccp-big.png" alt="">
            </div>
        </div>

        <div class="clearfix"></div>
    </div>
</div>

<div class="services">
    <div class="content">
        <div class="content-left">
            <h3>Let's Get Cheesy</h3>

            <h4>Private Events</h4>
            <p>Should you want to impress your investors or friends and relatives with your fine taste, I’m happy to consult with selections of cheese or to service your next event or give private demonstrations.</p>

            <h4>Parties</h4>
            <p>Lite catering is available as well as fondue and raclette courses, cheese platters and a small menu of horderves</p>

            <h4>Education</h4>
            <p>Need a history lesson, have a science question, or do you simply want to know what to pair with your food and drink? With over 7 years of knowledge and experience in fine foods and a scientific appreciation of happy accidents. I can set you on the right track to expanding your pallet, and your wealth of knowledge in the world’s oldest and most celebrated foods.</p>

            <h4>Tastings</h4>
            <p>As a fan of the industry and all who work in it, I am happy to help organize and host events for private establishments, such as hotels restaurants, winery’s and brewery’s. From as little as consultation or as much as ticketed events, I offer you my expertise.</p>
        </div>

        <div class="content-right mobile-hide">
            <div class="content-icon">
                <img src="img/tools.png" alt="">
            </div>
        </div>

        <div class="clearfix"></div>
    </div>
</div>

<div class="contact">
    <div class="content">
        <h3>Contact Me</h3>
        <p>Nam elementum quam vitae rutrum hendrerit. Nulla non odio in purus dignissim ultricies. Integer erat nibh, sollicitudin vitae justo at, euismod lobortis urna. Donec aliquet ornare leo. Maecenas sagittis lorem et lorem sagittis volutpat. Donec faucibus ultrices fringilla. Suspendisse tincidunt mauris quis lorem.</p>

        <div class="contact-results"></div>

        <div class="contact-form">
            <form action="send_message.php" id="contact-form">
                <div class="contact-field">
                    <label for="name">Name</label>
                    <input id="name" class="contact-input" name="name" type="text" value="" size="30" /><br />
                </div>
                <div class="contact-field">
                    <label for="email">Email</label>
                    <input id="email" class="contact-input" name="email" type="text" value="" size="30" /><br />
                </div>
                <div class="contact-field">
                    <label for="phone">Phone</label>
                    <input id="phone" class="contact-input" name="phone" type="text" value="" size="30" /><br />
                </div>
                <div class="contact-field">
                    <label for="message">Message</label>
                    <textarea id="message" class="contact-input" name="message" cols="30" rows="10"></textarea>
                </div>
                <div class="contact-field">
                    <?php echo $solvemedia ?>
                </div>
                <div class="contact-field">
                    <button>Send Message</button>
                </div>
            </form>
        </div>

    </div>
</div>

<?php include 'footer.phtml' ?>